export const REMOVE_APPOINTMENT_REQUEST = 'REMOVE_APPOINTMENT_REQUEST'
export const REMOVE_APPOINTMENT_SUCCESS = 'REMOVE_APPOINTMENT_SUCCESS'
export const REMOVE_APPOINTMENT_FAILURE = 'REMOVE_APPOINTMENT_FAILURE'