export const LOAD_APPOINTMENT_REQUEST = 'LOAD_APPOINTMENT_REQUEST'
export const LOAD_APPOINTMENT_SUCCESS = 'LOAD_APPOINTMENT_SUCCESS'
export const LOAD_APPOINTMENT_FAILURE = 'LOAD_APPOINTMENT_FAILURE'