export const EDIT_APPOINTMENT_REQUEST = 'EDIT_APPOINTMENT_REQUEST'
export const EDIT_APPOINTMENT_SUCCESS = 'EDIT_APPOINTMENT_SUCCESS'
export const EDIT_APPOINTMENT_FAILURE = 'EDIT_APPOINTMENT_FAILURE'