export const SEARCH_APPOINTMENT_REQUEST = 'SEARCH_APPOINTMENT_REQUEST'
export const SEARCH_APPOINTMENT_SUCCESS = 'SEARCH_APPOINTMENT_SUCCESS'
export const SEARCH_APPOINTMENT_FAILURE = 'SEARCH_APPOINTMENT_FAILURE'