export const LIST_APPOINTMENTS_REQUEST = 'LIST_APPOINTMENTS_REQUEST'
export const LIST_APPOINTMENTS_SUCCESS = 'LIST_APPOINTMENTS_SUCCESS'
export const LIST_APPOINTMENTS_FAILURE = 'LIST_APPOINTMENTS_FAILURE'