export const ORDER_APPOINTMENT_REQUEST = 'ORDER_APPOINTMENT_REQUEST'
export const ORDER_APPOINTMENT_SUCCESS = 'ORDER_APPOINTMENT_SUCCESS'
export const ORDER_APPOINTMENT_FAILURE = 'ORDER_APPOINTMENT_FAILURE'